uniswapv2:
  abi_path: "uniswapv2/abi/UniswapV2Router.abi.json"
  networks:
    mainnet:
      router_address: "0x9a489505a00cE272eAa5e07Dba6491314CaE3796"
    sepolia:
      router_address: "0xeE567Fe1712Faf6149d80dA1E6934E354124CfE3"
